//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime version :4.0.30319.42000
//
// Changes made to this file may cause incorrect behaviour and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Resources {
    using System;


    /// <summary>
    /// A strongly typed resource class intended, among other things, for viewing localised strings.
    /// </summary>
    // This class was generated automatically by the StronglyTypedResourceBuilder class
    // using a tool, such as ResGen or Visual Studio.
    // To add or remove a member, modify your .ResX file, then rerun ResGen
    // with the /str option or regenerate your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the CurrentUICulture property of the current thread for all
        /// resource searches using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Search for a localized channel similar to Press any key to continue....
        /// </summary>
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }

        /// <summary>
        /// Search for a localized string similar to Change Language.
        /// </summary>
        internal static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }

        /// <summary>
        /// Search for a localized string similar to Create Backup Job.
        /// </summary>
        internal static string create_job {
            get {
                return ResourceManager.GetString("create_job", resourceCulture);
            }
        }

        /// <summary>
        /// Search for a localized string similar to Delete Backup Job.
        /// </summary>
        internal static string delete_job {
            get {
                return ResourceManager.GetString("delete_job", resourceCulture);
            }
        }

        /// <summary>
        /// Search for a localized string similar to This program allows you to create and manage backup jobs...
        /// </summary>
        internal static string description1 {
            get {
                return ResourceManager.GetString("description1", resourceCulture);
            }
        }

        /// <summary>
        /// Search for a localized string similar to You can create, delete, and execute backup jobs...
        /// </summary>
        internal static string description2 {
            get {
                return ResourceManager.GetString("description2", resourceCulture);
            }
        }

        /// <summary>
        /// Searches for a localized string similar to Enter the code of country.
        /// </summary>
        internal static string enter_country_code {
            get {
                return ResourceManager.GetString("enter_country_code", resourceCulture);
            }
        }

        /// <summary>
        /// Search for a localized string similar to Enter the job number to delete:.
        /// </summary>
        internal static string enter_job_number_delete {
            get {
                return ResourceManager.GetString("enter_job_number_delete", resourceCulture);
            }
        }

        /// <summary>
        /// Search for a localized string similar to Enter the job number to execute:.
        /// </summary>
        internal static string enter_job_number_execute {
            get {
                return ResourceManager.GetString("enter_job_number_execute", resourceCulture);
            }
        }

        /// <summary>
        /// Search for a localized string similar to Enter the name of the job:.
        /// </summary>
        internal static string enter_name {
            get {
                return ResourceManager.GetString("enter_name", resourceCulture);
            }
        }

        /// <summary>
        /// Search for a localized string similar to Enter the source path:.
        /// </summary>
        internal static string enter_source {
            get {
                return ResourceManager.GetString("enter_source", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to Enter the target path:.
        /// </summary>
        internal static string enter_target {
            get {
                return ResourceManager.GetString("enter_target", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Execute Backup Job.
        /// </summary>
        internal static string execute_job {
            get {
                return ResourceManager.GetString("execute_job", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to Exiting the program....
        /// </summary>
        internal static string exiting {
            get {
                return ResourceManager.GetString("exiting", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to Invalid input. Please try again.
        /// </summary>
        internal static string invalid_input {
            get {
                return ResourceManager.GetString("invalid_input", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Invalid job number. Please try again.
        /// </summary>
        internal static string invalid_job {
            get {
                return ResourceManager.GetString("invalid_job", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Language code is invalid.
        /// </summary>
        internal static string invalid_language_code {
            get {
                return ResourceManager.GetString("invalid_language_code", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Invalid option. Please try again..
        /// </summary>
        internal static string invalid_option {
            get {
                return ResourceManager.GetString("invalid_option", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to Job created successfully!.
        /// </summary>
        internal static string job_created {
            get {
                return ResourceManager.GetString("job_created", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to Job deleted successfully!.
        /// </summary>
        internal static string job_deleted {
            get {
                return ResourceManager.GetString("job_deleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Job executed successfully!.
        /// </summary>
        internal static string job_executed {
            get {
                return ResourceManager.GetString("job_executed", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Job Name.
        /// </summary>
        internal static string job_name {
            get {
                return ResourceManager.GetString("job_name", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Source Path.
        /// </summary>
        internal static string job_source {
            get {
                return ResourceManager.GetString("job_source", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Target Path.
        /// </summary>
        internal static string job_target {
            get {
                return ResourceManager.GetString("job_target", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Type.
        /// </summary>
        internal static string job_type {
            get {
                return ResourceManager.GetString("job_type", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Language of the application English.
        /// </summary>
        internal static string langauge_application_english {
            get {
                return ResourceManager.GetString("langauge_application_english", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Language of the application french.
        /// </summary>
        internal static string language_application_français {
            get {
                return ResourceManager.GetString("language_application_français", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to Language has been changed.
        /// </summary>
        internal static string language_changed {
            get {
                return ResourceManager.GetString("language_changed", resourceCulture);
            }
        }

        /// <résumé>
        ///   Recherche une chaîne localisée semblable à List of Backup Jobs:.
        /// </summary>
        internal static string list_jobs {
            get {
                return ResourceManager.GetString("list_jobs", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized channel similar to Main Menu.
        /// </summary>
        internal static string main_menu {
            get {
                return ResourceManager.GetString("main_menu", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to No jobs available to delete.
        /// </summary>
        internal static string no_jobs {
            get {
                return ResourceManager.GetString("no_jobs", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to 1. Create Backup Job.
        /// </summary>
        internal static string option1 {
            get {
                return ResourceManager.GetString("option1", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to 2. Delete Backup Job.
        /// </summary>
        internal static string option2 {
            get {
                return ResourceManager.GetString("option2", resourceCulture);
            }
        }

        /// <summary>
        ///   Searches for a localized string similar to 3. Execute Backup Job.
        /// </summary>
        internal static string option3 {
            get {
                return ResourceManager.GetString("option3", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to 4. Change Language.
        /// </summary>
        internal static string option4 {
            get {
                return ResourceManager.GetString("option4", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to 5. Exit.
        /// </summary>
        internal static string option5 {
            get {
                return ResourceManager.GetString("option5", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized channel similar to Press any key to return to the main menu....
        /// </summary>
        internal static string press_return {
            get {
                return ResourceManager.GetString("press_return", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to Please select an option: .
        /// </summary>
        internal static string select_option {
            get {
                return ResourceManager.GetString("select_option", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized string similar to Select the type of backup (1 for Full, 2 for Differential):.
        /// </summary>
        internal static string select_type {
            get {
                return ResourceManager.GetString("select_type", resourceCulture);
            }
        }

        /// <summary>
        ///   Search for a localized channel similar to Welcome to the Backup Program!
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
