//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to continue....
        /// </summary>
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Language.
        /// </summary>
        internal static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Backup Job.
        /// </summary>
        internal static string create_job {
            get {
                return ResourceManager.GetString("create_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Backup Job.
        /// </summary>
        internal static string delete_job {
            get {
                return ResourceManager.GetString("delete_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This program allows you to create and manage backup jobs..
        /// </summary>
        internal static string description1 {
            get {
                return ResourceManager.GetString("description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can create, delete, and execute backup jobs..
        /// </summary>
        internal static string description2 {
            get {
                return ResourceManager.GetString("description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the code of country.
        /// </summary>
        internal static string enter_country_code {
            get {
                return ResourceManager.GetString("enter_country_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the job number to delete:.
        /// </summary>
        internal static string enter_job_number_delete {
            get {
                return ResourceManager.GetString("enter_job_number_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the job number to execute:.
        /// </summary>
        internal static string enter_job_number_execute {
            get {
                return ResourceManager.GetString("enter_job_number_execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of the job:.
        /// </summary>
        internal static string enter_name {
            get {
                return ResourceManager.GetString("enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the source path:.
        /// </summary>
        internal static string enter_source {
            get {
                return ResourceManager.GetString("enter_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the target path:.
        /// </summary>
        internal static string enter_target {
            get {
                return ResourceManager.GetString("enter_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute Backup Job.
        /// </summary>
        internal static string execute_job {
            get {
                return ResourceManager.GetString("execute_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exiting the program....
        /// </summary>
        internal static string exiting {
            get {
                return ResourceManager.GetString("exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid input. Please try again..
        /// </summary>
        internal static string invalid_input {
            get {
                return ResourceManager.GetString("invalid_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid job number. Please try again..
        /// </summary>
        internal static string invalid_job {
            get {
                return ResourceManager.GetString("invalid_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language code is invalid.
        /// </summary>
        internal static string invalid_language_code {
            get {
                return ResourceManager.GetString("invalid_language_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid option. Please try again..
        /// </summary>
        internal static string invalid_option {
            get {
                return ResourceManager.GetString("invalid_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job created successfully!.
        /// </summary>
        internal static string job_created {
            get {
                return ResourceManager.GetString("job_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job deleted successfully!.
        /// </summary>
        internal static string job_deleted {
            get {
                return ResourceManager.GetString("job_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job executed successfully!.
        /// </summary>
        internal static string job_executed {
            get {
                return ResourceManager.GetString("job_executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Name.
        /// </summary>
        internal static string job_name {
            get {
                return ResourceManager.GetString("job_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source Path.
        /// </summary>
        internal static string job_source {
            get {
                return ResourceManager.GetString("job_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target Path.
        /// </summary>
        internal static string job_target {
            get {
                return ResourceManager.GetString("job_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string job_type {
            get {
                return ResourceManager.GetString("job_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language of the application english.
        /// </summary>
        internal static string langauge_application_english {
            get {
                return ResourceManager.GetString("langauge_application_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language of the application french.
        /// </summary>
        internal static string language_application_français {
            get {
                return ResourceManager.GetString("language_application_français", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language has been changed.
        /// </summary>
        internal static string language_changed {
            get {
                return ResourceManager.GetString("language_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Backup Jobs:.
        /// </summary>
        internal static string list_jobs {
            get {
                return ResourceManager.GetString("list_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main Menu.
        /// </summary>
        internal static string main_menu {
            get {
                return ResourceManager.GetString("main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No jobs available to delete..
        /// </summary>
        internal static string no_jobs {
            get {
                return ResourceManager.GetString("no_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Create Backup Job.
        /// </summary>
        internal static string option1 {
            get {
                return ResourceManager.GetString("option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Delete Backup Job.
        /// </summary>
        internal static string option2 {
            get {
                return ResourceManager.GetString("option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Execute Backup Job.
        /// </summary>
        internal static string option3 {
            get {
                return ResourceManager.GetString("option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Change Language.
        /// </summary>
        internal static string option4 {
            get {
                return ResourceManager.GetString("option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5. Exit.
        /// </summary>
        internal static string option5 {
            get {
                return ResourceManager.GetString("option5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to return to the main menu....
        /// </summary>
        internal static string press_return {
            get {
                return ResourceManager.GetString("press_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select an option: .
        /// </summary>
        internal static string select_option {
            get {
                return ResourceManager.GetString("select_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the type of backup (1 for Full, 2 for Differential):.
        /// </summary>
        internal static string select_type {
            get {
                return ResourceManager.GetString("select_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to the Backup Program!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
